### ISSUE TITLE
Hi from Rotations.jl

### ISSUE THREAD

**Issue by c42f** [RoboticExplorationLab/DifferentialRotations.jl#1]
I just noticed this package; I wondered whether you'd consider working with us to improve Rotations.jl instead of starting again with yet-another-rotations-package. I'm currently trying to get Rotations.jl moved into a more clearly community-maintained location such as JuliaGeometry and would be happy to add collaborators.

The original goals for Rotations included optimization and taking derivatives, so I think there's almost a complete overlap of high level goals. We have functions for Jacobians and I think your `MRP` type is simply our `SPQuat`, or very closely related.

One obvious difference is that we made the choice `Rotation.Rotation{N} <: StaticMatrix{N,N,T}` which means a `Rotation` is explicitly a linear map. I'm not sure whether this would be disruptive to the APIs you've already defined here?

CC @tkoolen who was very active in the Julia Robotics space and graciously maintained Rotations.jl for a while (though I think he's now doing other things).

**Comment by c42f** [comment]
PS, of course it's clear that this package is in early days (though already with impressive functionality), and it's good to experiment with alternative ways to do things. But in this case I feel like we might actually be trying to do the same thing, just with incompatible APIs!

Anyway, give it some thought, and I wish you the best with this package regardless of how you choose!

**Comment by bjack205** [comment]
I'm definitely interested in merging these two packages. I borrowed pretty heavily from both Rotations.jl and Quaternions.jl when creating this package. 

I put together this package since I needed quaternions parameterized by the quaternion by the "retraction map" that maps the quaternion to it's local 3D approximation. I used this as part of a recent [paper](https://rexlab.stanford.edu/papers/planning_with_attitude.pdf) we submitted for doing planning and control on SE(3).

Yes, as you pointed out the biggest difference is that I'm not inheriting from a `StaticMatrix`. I just tried inheriting from `StaticMatrix` and it didn't effect performance at all, so this shouldn't be a problem (see new `rotationsjl` branch).

The only real difference is in the parameterization of the quaternion. If we can somehow merge that functionality into Rotations.jl it should be a fairly straight-forward merge between packages.

**Comment by c42f** [comment]
Great, I'm in the process of moving Rotations now (https://github.com/FugroRoames/Rotations.jl/issues/110).

**Comment by c42f** [comment]
> I just tried inheriting from StaticMatrix and it didn't effect performance at all, so this shouldn't be a problem (see new rotationsjl branch).

Sounds great! My main concern is whether the packages are algebraically compatible in the sense that a proposed `UnitQuaternion <: Rotation <: SMatrix{3,3}` should then have all the algebraic properties of a 3x3 matrix. Does this conflict with some of the standard quaternion algebra? A clean solution to that could be a separate Quaternion type which is wrapped to make it into a RotationQuaterion or some such thing. Hope I'm not over thinking this.

> The only real difference is in the parameterization of the quaternion. If we can somehow merge that functionality into Rotations.jl it should be a fairly straight-forward merge between packages.

For sure; if you've got a better parameterization (faster or whatever) I think we could do a round of deprecations. The types have different names at the moment anyway.

By the way, for integrating hand-written derivatives with AD tools in a systematic way there's the very recent package ChainRulesCore.jl which might be interesting: http://www.juliadiff.org/ChainRulesCore.jl/dev/. I'm not sure how that package is tracking for integration with all the autodiff tooling but the general idea seems like the right thing.

**Comment by c42f** [comment]
Rotations is now moved to https://github.com/JuliaGeometry/Rotations.jl and I'm modernizing our CI infrastructure, etc to make contribution easier.

**Comment by c42f** [comment]
The initial merge is done, thanks so much :-)
